const preloadedRecipes = [
    { id: 1, name: "Asian Chicken and Orange Chopped Salad", ings: ["chicken thighs", "romaine lettuce", "strawberries", "orange", "cucumber", "cilantro", "peanuts", "sesame ginger vinaigrette"] },
    { id: 2, name: "Basil Butter Chicken and Tomatoes", ings: ["chicken breasts", "lemon pepper seasoning", "butter", "grape tomatoes", "fresh basil"] },
    { id: 3, name: "Big Easy Baked Chicken Thighs", ings: ["chicken thighs", "Cajun seasoning", "lime juice", "dried rosemary", "salt", "pepper"] },
    { id: 4, name: "California Skillet Chicken", ings: ["bacon", "chicken breasts", "grape tomatoes", "ranch dressing", "chipotle chile pepper", "Monterey Jack cheese", "avocados", "cilantro"] },
    { id: 5, name: "Chicken and Ramen Stir Fry", ings: ["chicken breasts", "ramen noodles", "frozen vegetable stir fry medley", "mushrooms", "stir fry sauce"] },
    { id: 6, name: "Chicken Marsala Risotto-Style Orzo", ings: ["butter", "mushrooms", "onion", "garlic", "orzo", "Marsala wine", "chicken broth", "frozen chopped spinach", "Parmesan cheese", "chicken breasts"] },
    { id: 7, name: "Chicken Tortilla Soup", ings: ["chicken breasts", "chicken broth", "diced tomatoes", "Southwest vegetable blend", "enchilada sauce", "garlic", "cumin", "chili powder", "avocado", "Cheddar cheese", "corn tortillas"] },
    { id: 8, name: "Chicken-Vegetable Rice Noodles", ings: ["rice noodles", "stir fry vegetables", "rotisserie chicken", "teriyaki sauce", "cashews"] },
    { id: 9, name: "Chipotle Chicken and Rice Soup", ings: ["onion", "jalapeno peppers", "chicken breasts", "taco seasoning", "chipotle chile pepper", "chicken broth", "fire roasted diced tomatoes", "limes", "white rice", "black beans"] },
    { id: 10, name: "Easy Tex-Mex Chicken", ings: ["white rice", "chicken breasts", "taco seasoning", "black beans", "frozen corn", "salsa"] },
    { id: 11, name: "All-American Burger Bowls", ings: ["ground beef", "chili sauce", "Worcestershire sauce", "yellow mustard", "Cheddar cheese", "romaine lettuce", "tomatoes", "red onion", "fries"] },
    { id: 12, name: "Beef and Broccoli Lo Mein", ings: ["lo mein noodles", "broccoli florets", "flank steak", "carrots", "brown sugar", "soy sauce", "hoisin sauce", "sesame oil"] },
    { id: 13, name: "Enchilada Soup", ings: ["ground beef", "pinto beans", "onion", "jalapeño peppers", "garlic", "chicken broth", "petite diced tomatoes", "chili powder", "cumin"] },
    { id: 14, name: "Mississippi Pot Roast", ings: ["sirloin tip roast", "Ranch dressing mix", "Au Jus mix", "butter", "peperoncini peppers"] },
    { id: 15, name: "Bruschetta Pork Chops", ings: ["pork chops", "grape tomatoes", "bruschetta topping", "fresh basil", "garlic", "fresh thyme", "balsamic vinegar"] },
    { id: 16, name: "Orange-Balsamic Pork Tenderloin", ings: ["pork tenderloin", "orange juice", "balsamic vinegar", "garlic", "fresh thyme"] },
    { id: 17, name: "Rosemary-Mustard Pork Chops", ings: ["pork chops", "olive oil", "Dijon mustard", "fresh rosemary", "red wine vinegar"] },
    { id: 18, name: "Sheet Pan Creole Shrimp and Sausage", ings: ["onion", "bell pepper", "kielbasa sausage", "avocado oil", "Cajun Creole seasoning", "shrimp", "grape tomatoes", "fresh parsley"] },
    { id: 19, name: "Shrimp Caesar Pasta", ings: ["spaghetti", "shrimp", "olive oil", "Caesar dressing", "fresh parsley"] },
    { id: 20, name: "Spicy Orange-Glazed Shrimp", ings: ["orange juice", "soy sauce", "crushed red pepper", "shrimp", "olive oil", "green onions"] },
    { id: 21, name: "Tacos de Mario", ings: ["tortillas", "marinated meat", "onion", "cilantro", "tomatoes"] },
    { id: 22, name: "Mississippi Pot Roast", ings: ["1 1/2 lb sirloin tip roast", "2 tbsp ranch dressing mix", "1 pkg au jus mix", "1/2 cup butter", "6 peperoncini peppers"] },
    { id: 23, name: "Ancho Chile Pot Roast", ings: ["4 large dried ancho chile peppers", "3 1/2 lb boneless chuck roast", "2 tbsp avocado oil", "1 onion", "2 lb sweet potatoes", "3 cups beef bone broth", "fresh thyme", "2 bay leaves"] },
    { id: 24, name: "Balsamic-Mustard Flank Steak", ings: ["2 lb flank steak", "2 cloves garlic", "1 tsp salt", "1 tsp pepper", "2 tbsp avocado oil", "3/4 cup balsamic vinegar", "1/3 cup dijon mustard"] },
    { id: 25, name: "Beef and Broccoli Lo Mein", ings: ["1 pkg lo mein noodles", "1 lb flank steak", "2 tbsp olive oil", "1 pkg shredded carrots", "1/2 cup brown sugar", "1/2 cup soy sauce", "1/4 cup hoisin sauce", "1 tbsp sesame oil"] },
    { id: 26, name: "Brown Sugar Pork Roast", ings: ["1 1/2 tsp brown sugar", "1 tsp salt", "1 tsp pepper", "1.5 lb pork shoulder roast", "1 cup onion", "2 cloves garlic", "1 bay leaf", "1/2 cup chicken broth", "1/4 cup white wine vinegar"] },
    { id: 27, name: "Creole Pork Chops", ings: ["6 bone in pork chops", "1 tsp creole seasoning", "2 stalks celery", "1 onion", "1 green bell pepper", "1 pint grape tomatoes", "2 cloves garlic", "2 tbsp fresh parsley"] },
    { id: 28, name: "Rosemary-Mustard Pork Chops", ings: ["2 lb boneless pork chops", "1/2 tsp salt", "1/2 tsp pepper", "1/4 cup olive oil", "1/4 cup dijon mustard", "1 tbsp fresh rosemary", "2 tsp red wine vinegar"] },
    { id: 29, name: "Sheet Pan Creole Shrimp and Sausage", ings: ["1 small onion", "1 red bell pepper", "1 yellow bell pepper", "14 oz kielbasa sausage", "1/4 cup avocado oil", "1 tbsp cajun creole seasoning", "1 lb large raw shrimp", "1 pint grape tomatoes", "1/4 cup fresh parsley"] },
    { id: 30, name: "Shrimp Caesar Pasta", ings: ["4 oz spaghetti", "1/2 lb large raw shrimp", "1 tsp olive oil", "1/2 cup vinaigrette caesar dressing", "3 tbsp fresh parsley"] },
    { id: 31, name: "Shrimp Scampi", ings: ["16 oz angel hair pasta", "4 cloves garlic", "2 tbsp olive oil", "2 lb raw shrimp", "1/2 cup white wine", "3 tbsp fresh lemon juice", "3 tbsp butter", "1/4 tsp crushed red pepper", "1/4 cup fresh parsley"] },
    { id: 32, name: "Spicy Orange-Glazed Shrimp", ings: ["3/4 cup orange juice", "2 tbsp soy sauce", "1/2 tsp crushed red pepper", "2 lb large raw shrimp", "1/2 tsp salt", "1 tbsp olive oil", "2 green onions"] },
    { id: 33, name: "Tortellini Florentine Soup", ings: ["3 plant based sausage links", "1 1/2 tbsp minced garlic", "4 cups vegetable juice", "32 oz vegetable broth", "12 oz cheese tortellini", "10 oz frozen chopped spinach"] },
    { id: 34, name: "Crockpot Chicken Tacos", ings: ["2 lb chicken breasts", "1 jar salsa", "1 pkg taco seasoning", "tortillas", "shredded lettuce", "cheddar cheese"] },
    { id: 35, name: "Honey Roasted Tomatoes with Chicken", ings: ["1.5 lb chicken breasts", "1 pint grape tomatoes", "2 tbsp honey", "1 tbsp balsamic vinegar", "1/2 tsp salt", "1/4 cup fresh basil"] },
    { id: 36, name: "Italian Chicken Bowls", ings: ["1 cup orzo", "1/4 cup olive oil vinaigrette", "1.5 lb chicken thighs", "1 tsp italian seasoning", "1/2 tsp garlic powder", "1 cup grape tomatoes", "1/4 cup red onion", "4 oz mozzarella pearls"] },
    { id: 37, name: "Lemon Chicken Piccata", ings: ["1 lb chicken breasts", "1 egg", "1 tbsp lemon juice", "1/4 cup flour", "1/2 tsp paprika", "1/2 tsp garlic powder", "2 tbsp butter", "1 tsp chicken bouillon"] },
    { id: 38, name: "Pesto Chicken and Asparagus Pasta", ings: ["8 oz rotini pasta", "1 lb asparagus", "1 rotisserie chicken", "1/2 cup pesto", "1/4 cup half and half", "1/2 tsp onion powder", "1/2 tsp garlic powder"] },
    { id: 39, name: "Sausage and Shrimp Skillet", ings: ["12 oz smoked turkey sausage", "1 onion", "1 bell pepper", "2 cloves garlic", "2 zucchini", "1 can fire roasted tomatoes", "1/2 cup chicken broth", "1/2 lb shrimp"] },
    { id: 40, name: "White Queso Chicken Nachos", ings: ["1 bag multigrain tortilla chips", "1 cup white cheese dip", "1 rotisserie chicken", "1/2 cup salsa", "1/4 cup red onion", "1 avocado", "2 oz queso fresco", "1/4 cup cilantro"] },
    { id: 41, name: "Zucchini and Chicken Skillet", ings: ["1.5 lb chicken breasts", "2 zucchini", "1 can diced tomatoes", "1 tsp italian seasoning", "1/2 cup parmesan cheese"] }
];