const preloadedRecipes = [
    // --- CHICKEN ---
    { id: 1, name: "Asian Chicken and Orange Chopped Salad", ings: ["chicken thighs", "romaine lettuce", "strawberries", "orange", "cucumber", "cilantro", "peanuts", "sesame ginger vinaigrette"] },
    { id: 2, name: "Basil Butter Chicken and Tomatoes", ings: ["chicken breasts", "lemon pepper seasoning", "butter", "grape tomatoes", "fresh basil"] },
    { id: 3, name: "Big Easy Baked Chicken Thighs", ings: ["chicken thighs", "Cajun seasoning", "lime juice", "dried rosemary", "salt", "pepper"] },
    { id: 4, name: "California Skillet Chicken", ings: ["bacon", "chicken breasts", "grape tomatoes", "ranch dressing", "chipotle chile pepper", "Monterey Jack cheese", "avocados", "cilantro"] },
    { id: 5, name: "Chicken and Ramen Stir Fry", ings: ["chicken breasts", "ramen noodles", "frozen vegetable stir fry medley", "mushrooms", "stir fry sauce"] },
    { id: 6, name: "Chicken Marsala Risotto-Style Orzo", ings: ["butter", "mushrooms", "onion", "garlic", "orzo", "Marsala wine", "chicken broth", "frozen chopped spinach", "Parmesan cheese", "chicken breasts", "Italian seasoning"] },
    { id: 7, name: "Chicken Nachos with White Queso", ings: ["tortilla chips", "white cheese dip", "rotisserie chicken", "salsa", "red onion", "avocado", "queso fresco", "cilantro"] },
    { id: 8, name: "Chicken Piccata", ings: ["chicken breasts", "egg", "lemon juice", "flour", "paprika", "garlic powder", "butter", "chicken bouillon"] },
    { id: 9, name: "Chicken Tortilla Soup", ings: ["chicken breasts", "chicken broth", "diced tomatoes", "Southwest vegetable blend", "enchilada sauce", "garlic", "cumin", "chili powder", "avocado", "Cheddar cheese", "corn tortillas"] },
    { id: 10, name: "Chicken-Vegetable Rice Noodles", ings: ["rice noodles", "stir fry vegetables", "rotisserie chicken", "teriyaki sauce", "cashews"] },
    { id: 11, name: "Chicken with Honey-Roasted Tomatoes", ings: ["chicken breasts", "grape tomatoes", "honey", "balsamic vinegar", "fresh basil"] },
    { id: 12, name: "Chipotle Chicken and Rice Soup", ings: ["onion", "jalapeno peppers", "chicken breasts", "taco seasoning", "chipotle chile pepper", "chicken broth", "fire roasted diced tomatoes", "limes", "white rice", "black beans", "cilantro"] },
    { id: 13, name: "Easy Tex-Mex Chicken", ings: ["white rice", "chicken breasts", "taco seasoning", "black beans", "frozen corn", "salsa"] },
    { id: 14, name: "Italian Chicken Bowls", ings: ["orzo", "olive oil vinaigrette", "chicken thighs", "Italian seasoning", "garlic powder", "grape tomatoes", "red onion", "mozzarella pearls"] },
    { id: 15, name: "Italian Chicken Spaghetti Soup", ings: ["mirepoix", "chicken broth", "Italian seasoning", "rotisserie chicken", "spaghetti", "sun dried tomatoes", "Parmesan cheese"] },
    { id: 16, name: "Montreal Chicken", ings: ["chicken breasts", "Montreal steak seasoning", "olive oil"] },
    { id: 17, name: "Pesto Chicken and Asparagus Pasta", ings: ["rotini pasta", "asparagus", "rotisserie chicken", "pesto", "half and half", "onion powder", "garlic powder"] },
    { id: 18, name: "Roasted Chicken Thighs", ings: ["red grapes", "red onions", "fresh thyme", "chicken thighs"] },
    { id: 19, name: "Sheet Pan Chicken Fajitas", ings: ["chicken breasts", "bell peppers", "onion", "Roma tomatoes", "Mexican seasoning", "romaine lettuce", "avocados", "limes"] },
    { id: 20, name: "Sheet Pan Sesame Chicken and Broccoli", ings: ["sesame oil", "soy sauce", "gochujang", "chicken thighs", "broccoli florets", "red bell peppers", "honey", "sesame seeds"] },
    { id: 21, name: "Skillet Lemon Chicken", ings: ["chicken breasts", "dried thyme", "butter", "chicken broth", "lemon juice", "honey", "Dijon mustard", "lemon"] },
    { id: 22, name: "Spring Chicken and Vegetables", ings: ["chicken breasts", "parsley", "white wine vinegar", "green onions", "asparagus", "green peas", "goat cheese", "linguine", "panko breadcrumbs"] },
    { id: 23, name: "Stovetop Chicken and Potatoes", ings: ["chicken thighs", "red potatoes", "Italian seasoning", "garlic", "heavy cream", "butter", "lemon juice", "green peas"] },
    { id: 24, name: "Chicken and Wild Rice Soup", ings: ["chicken broth", "chicken breasts", "celery", "carrots", "wild rice mix", "onion", "black pepper"] },
    { id: 25, name: "Instant Pot Arroz Con Pollo", ings: ["olive oil", "butter", "saffron", "onion", "red bell pepper", "garlic", "chicken thighs", "chorizo", "white wine", "chicken broth", "diced tomatoes", "yellow rice", "lime", "paprika", "cumin", "chili powder"] },
    { id: 26, name: "Instant Pot Chicken Fajita Soup", ings: ["vegetable oil", "bell peppers", "onions", "chicken broth", "yellow rice", "chicken breasts", "fajita seasoning", "Mexican cheese"] },
    { id: 27, name: "Instant Pot Chicken Teriyaki", ings: ["chicken thighs", "sesame oil", "butter", "garlic", "ginger", "chicken broth", "rice vinegar", "soy sauce", "brown sugar", "hoisin sauce", "honey", "scallions"] },

    // --- BEEF ---
    { id: 28, name: "All-American Burger Bowls", ings: ["ground beef", "chili sauce", "Worcestershire sauce", "yellow mustard", "Cheddar cheese", "romaine lettuce", "tomatoes", "red onion", "French Fries"] },
    { id: 29, name: "Ancho Chile Pot Roast", ings: ["ancho chile peppers", "chuck roast", "avocado oil", "onion", "garlic", "sweet potatoes", "beef bone broth", "fresh thyme", "bay leaves"] },
    { id: 30, name: "Balsamic-Mustard Flank Steak", ings: ["flank steak", "garlic", "balsamic vinegar", "Dijon mustard"] },
    { id: 31, name: "Barbecue Flank Steak and Corn Salad", ings: ["flank steak", "barbecue sauce", "corn", "avocados", "Roma tomatoes"] },
    { id: 32, name: "Beef and Broccoli Lo Mein", ings: ["lo mein noodles", "broccoli florets", "flank steak", "shredded carrots", "brown sugar", "soy sauce", "hoisin sauce", "sesame oil", "garlic powder", "red pepper"] },
    { id: 33, name: "Beef Roast with Vegetables", ings: ["eye of round roast", "carrots", "parsnips", "turnips", "celery", "fresh thyme", "garlic", "leeks"] },
    { id: 34, name: "Bistro Flank Steak", ings: ["flank steak", "dry mustard", "garlic powder", "dried oregano"] },
    { id: 35, name: "BLT Steak Salad", ings: ["sirloin steak", "Montreal steak seasoning", "spinach", "tomatoes", "red onion", "bacon", "olive oil", "red wine vinegar", "Dijon mustard", "garlic"] },
    { id: 36, name: "Coffee-braised Beef Brisket", ings: ["ancho chile powder", "baking cocoa", "dried oregano", "cumin", "chipotle chile pepper", "beef brisket", "red onion", "garlic", "coffee", "balsamic vinegar"] },
    { id: 37, name: "Enchilada Soup", ings: ["ground beef", "pinto beans", "onion", "jalapeño peppers", "garlic", "chicken broth", "diced tomatoes", "chili powder", "cumin", "tortilla strips"] },
    { id: 38, name: "Garlic Butter Steak and Potatoes", ings: ["red potato wedges", "garlic", "sirloin steak", "butter", "spring mix", "tomatoes", "cucumber", "mozzarella pearls", "Italian dressing"] },
    { id: 39, name: "Herb Butter Bistro Steaks", ings: ["strip steaks", "shallots", "red wine vinegar", "lemon juice", "butter", "fresh parsley", "fresh thyme"] },
    { id: 40, name: "Italian Beefy Pasta Bake", ings: ["ground beef", "onion", "red bell pepper", "fire roasted tomatoes", "chicken broth", "Italian seasoning", "penne pasta", "Parmesan cheese"] },
    { id: 41, name: "Kung Pao Beef and Vegetables", ings: ["white rice", "ground beef", "broccoli stir fry vegetables", "kung pao sauce"] },
    { id: 42, name: "Mississippi Pot Roast", ings: ["sirloin tip roast", "Ranch dressing mix", "Au Jus mix", "butter", "peperoncini peppers"] },
    { id: 43, name: "Sheet Pan Herbed Flank Steak", ings: ["flank steak", "fresh rosemary", "fresh thyme", "garlic"] },
    { id: 44, name: "Sheet-Pan Steak with Broccolini", ings: ["balsamic vinegar", "avocado oil", "Dijon mustard", "garlic", "skirt steak", "Broccolini", "walnuts"] },
    { id: 45, name: "Spicy Beef Ramen", ings: ["beef ramen soup", "beef broth", "skirt steak", "garlic", "red pepper", "green onions", "eggs"] },
    { id: 46, name: "Spicy Ginger Steak", ings: ["sirloin steaks", "soy sauce", "ginger", "chili garlic paste", "rice vinegar", "honey", "sesame oil", "baby bok choy"] },
    { id: 47, name: "Best Ever Instant Pot Roast", ings: ["chuck roast", "Portobello mushrooms", "beef broth", "red wine", "baby carrots", "baby white potatoes", "onions", "garlic", "Worcestershire sauce"] },
    { id: 48, name: "Instant Pot Beef Bourguignon", ings: ["beef cubes", "bacon", "butter", "garlic", "tomato paste", "red wine", "beef broth", "pearl onions", "mushrooms"] },
    { id: 49, name: "Instant Pot Spaghetti & Meatballs", ings: ["meatballs", "marinara sauce", "spaghetti", "cherry tomatoes", "Parmesan cheese", "broth", "shallots", "garlic"] },

    // --- PORK ---
    { id: 50, name: "Brown Sugar Pork Roast", ings: ["brown sugar", "pork shoulder roast", "onion", "garlic", "bay leaf", "chicken broth", "white wine vinegar"] },
    { id: 51, name: "Bruschetta Pork Chops", ings: ["pork chops", "grape tomatoes", "bruschetta topping", "fresh basil", "garlic", "fresh thyme", "balsamic vinegar"] },
    { id: 52, name: "Creole Pork Chops", ings: ["pork chops", "Creole seasoning", "celery", "onion", "green bell pepper", "grape tomatoes", "garlic", "fresh parsley"] },
    { id: 53, name: "Grilled Lemon-Pepper Pork Chops", ings: ["lemon pepper seasoning", "pork loin chops"] },
    { id: 54, name: "Grilled Greek Pork Medallions", ings: ["pine nuts", "garlic", "flour", "Greek seasoning", "pork tenderloins"] },
    { id: 55, name: "Honey Garlic Pork Tenderloin", ings: ["pork tenderloins", "garlic", "honey", "soy sauce", "rice vinegar", "green onions"] },
    { id: 56, name: "Lemon and Herb Pork Tenderloin", ings: ["lemon juice", "fresh thyme", "fresh rosemary", "garlic", "pork tenderloins"] },
    { id: 57, name: "One Pot Pork Chops and Rice", ings: ["pork chops", "smoked paprika", "bell pepper", "grape tomatoes", "chicken broth", "fresh thyme", "brown rice"] },
    { id: 58, name: "Orange-Balsamic Pork Tenderloin", ings: ["orange", "balsamic vinegar", "pork tenderloins", "garlic", "fresh thyme"] },
    { id: 59, name: "Pork and Apples", ings: ["pork chops", "apples", "brown sugar", "cinnamon", "butter"] },
    { id: 60, name: "Pork Chops with Balsamic-Bacon Sauce", ings: ["bacon", "pork chops", "red onion", "garlic", "chicken broth", "balsamic vinegar", "mustard"] },
    { id: 61, name: "Pork Tenderloin with Chimichurri", ings: ["pork tenderloins", "parsley", "red wine vinegar", "fresh oregano", "red pepper", "garlic"] },
    { id: 62, name: "Rosemary-Mustard Pork Chops", ings: ["pork chops", "Dijon mustard", "fresh rosemary", "red wine vinegar", "garlic", "honey"] },
    { id: 63, name: "Skillet Salsa Pork Chops", ings: ["pork chops", "garlic salt", "cumin", "salsa", "lime juice"] },
    { id: 64, name: "Slow Cooker Pork Ramen", ings: ["pork shoulder", "onion", "garlic", "ginger", "chicken broth", "leek", "mushrooms", "soy sauce", "ramen noodles", "green onions"] },
    { id: 65, name: "Smoky Pork Tenderloin & Sweet Potatoes", ings: ["pork tenderloins", "smoked paprika", "sweet potatoes", "garlic powder", "broccoli florets"] },
    { id: 66, name: "Tex-Mex Pork Chops", ings: ["pork chops", "taco seasoning", "salsa verde"] },
    { id: 67, name: "Root Beer BBQ Pulled Pork", ings: ["pork shoulder roast", "barbecue sauce", "root beer", "onion soup mix"] },
    { id: 68, name: "Instant Pot Pork Loin", ings: ["pork loin roast", "butter", "garlic", "brown sugar", "soy sauce", "lemon zest", "parsley", "thyme", "chicken broth"] },

    // --- SEAFOOD & PASTA ---
    { id: 69, name: "Bruschetta Pasta", ings: ["linguine", "baby spinach", "garlic", "tomatoes", "fresh basil", "balsamic vinegar", "Parmesan cheese"] },
    { id: 70, name: "Creole Shrimp", ings: ["lemons", "shrimp", "Creole seasoning", "butter"] },
    { id: 71, name: "Italian Shrimp and Pasta", ings: ["fettuccine", "butter", "Italian dressing mix", "shrimp", "grape tomatoes"] },
    { id: 72, name: "Lowcountry Sausage and Shrimp Skillet", ings: ["turkey sausage", "onion", "bell pepper", "garlic", "zucchini", "fire roasted tomatoes", "chicken broth", "shrimp"] },
    { id: 73, name: "Red Beans and Rice", ings: ["smoked sausage", "dried red beans", "onion", "bell pepper", "celery", "Cajun seasoning", "chicken broth", "white rice"] },
    { id: 74, name: "Sheet Pan Creole Shrimp and Sausage", ings: ["onion", "bell pepper", "kielbasa sausage", "Cajun Creole seasoning", "shrimp", "grape tomatoes", "parsley"] },
    { id: 75, name: "Shrimp Caesar Pasta", ings: ["spaghetti", "shrimp", "Caesar dressing", "parsley"] },
    { id: 76, name: "Shrimp Scampi", ings: ["angel hair pasta", "garlic", "shrimp", "white wine", "lemon juice", "butter", "red pepper", "parsley"] },
    { id: 77, name: "Spicy Orange-Glazed Shrimp", ings: ["orange juice", "soy sauce", "red pepper", "shrimp", "green onions"] },
    { id: 78, name: "Burst Cherry Tomato Pasta", ings: ["pasta", "olive oil", "garlic", "cherry tomatoes", "basil", "Parmesan"] },
    { id: 79, name: "Creamy Mozzarella Shrimp Pasta", ings: ["penne pasta", "shrimp", "garlic", "sun-dried tomatoes", "half and half", "mozzarella cheese", "basil"] },
    { id: 80, name: "Espagueti Verde", ings: ["poblano peppers", "cilantro", "Mexican crema", "garlic", "spaghetti", "queso fresco"] },
    { id: 81, name: "Instant Pot Paella", ings: ["chicken thighs", "chorizo", "shrimp", "scallops", "onion", "bell pepper", "garlic", "rice", "chicken broth", "white wine", "peas", "saffron"] },

    // --- BAKING & DESSERTS ---
    { id: 82, name: "Banana Poppy Muffins", ings: ["banana", "poppy seed", "milk", "egg", "sugar", "vegetable oil", "flour", "baking powder", "salt"] },
    { id: 83, name: "BB Is For Banana Bread", ings: ["sugar", "mashed bananas", "vegetable oil", "eggs", "milk", "flour", "nuts", "baking soda", "cinnamon"] },
    { id: 84, name: "Black Bottom Cupcakes", ings: ["cream cheese", "egg", "chocolate chips", "butterscotch chips", "flour", "baking soda", "cocoa", "sugar", "oil", "vanilla"] },
    { id: 85, name: "Buffalo Layer Cake", ings: ["molasses", "egg", "butter", "flour", "cinnamon", "cloves", "nutmeg", "baking soda"] },
    { id: 86, name: "Cherry Pecan Bread", ings: ["butter", "sugar", "eggs", "vanilla", "flour", "baking soda", "buttermilk", "pecans", "maraschino cherries"] },
    { id: 87, name: "Coconut Chocolate Chip Cookies", ings: ["coconut", "condensed milk", "baking powder", "chocolate chips"] },
    { id: 88, name: "Coffee Cake", ings: ["flour", "sugar", "baking powder", "vegetable oil", "milk", "egg", "brown sugar", "cinnamon", "butter"] },
    { id: 89, name: "Easy Amaretto Chocolate Truffles", ings: ["chocolate chips", "Amaretto", "heavy cream", "almonds"] },
    { id: 90, name: "Fruit Pizza", ings: ["cookie dough", "cream cheese", "sugar", "pineapple", "orange juice", "lemon juice", "fruit"] },
    { id: 91, name: "Italian Cookies", ings: ["eggs", "sugar", "vegetable oil", "lemon extract", "flour", "baking powder", "confectionary sugar"] },
    { id: 92, name: "Oatmeal Raisin Cookies", ings: ["butter", "brown sugar", "sugar", "eggs", "vanilla", "flour", "baking soda", "cinnamon", "oats", "raisins"] },

    // --- MISC & SOUPS ---
    { id: 93, name: "Egg Drop Wonton Soup", ings: ["broth", "ginger", "garlic powder", "sesame oil", "scallions", "wontons", "eggs"] },
    { id: 94, name: "Instant Pot Pozole", ings: ["onion", "poblano pepper", "jalapeño peppers", "garlic", "broth", "hominy", "pork shoulder", "dried chiles"] },
    { id: 95, name: "Tortellini Florentine Soup", ings: ["sausage links", "garlic", "vegetable juice", "vegetable broth", "cheese tortellini", "frozen chopped spinach"] },
    { id: 96, name: "Tacos de Mario", ings: ["tortillas", "marinated meat", "onion", "cilantro", "tomatoes"] }
];

