const preloadedRecipes = [
    // --- CHICKEN ---
    { id: 1, name: "Asian Chicken and Orange Chopped Salad", ings: ["chicken thighs", "salt", "pepper", "ground ginger", "olive oil", "romaine lettuce", "strawberries", "orange sections", "cucumber", "cilantro", "peanuts", "sesame ginger vinaigrette"] },
    { id: 2, name: "Basil Butter Chicken and Tomatoes", ings: ["chicken breasts", "lemon pepper seasoning", "butter", "grape tomatoes", "fresh basil"] },
    { id: 3, name: "Big Easy Baked Chicken Thighs", ings: ["Cajun seasoning", "lime juice", "dried rosemary", "salt", "pepper", "chicken thighs"] },
    { id: 4, name: "California Skillet Chicken", ings: ["bacon", "chicken breasts", "salt", "pepper", "grape tomatoes", "refrigerated yogurt Ranch dressing", "ground chipotle chile pepper", "Monterey Jack cheese", "avocados", "fresh cilantro"] },
    { id: 5, name: "Chicken and Ramen Stir Fry", ings: ["chicken breasts", "vegetable oil", "water", "chicken flavored ramen noodles", "frozen vegetable stir fry medley", "mushrooms", "stir fry sauce"] },
    { id: 6, name: "Chicken and Rice", ings: ["Chicken", "Rice", "Chicken broth", "Sazon packet"] },
    { id: 7, name: "Chicken Marsala Risotto-Style Orzo", ings: ["butter", "mushrooms", "onion", "garlic", "orzo", "Marsala wine", "chicken broth", "frozen chopped spinach", "shredded Parmesan cheese", "chicken breasts", "Italian seasoning", "salt", "pepper", "olive oil"] },
    { id: 8, name: "Chicken Nachos with White Queso", ings: ["multigrain tortilla chips", "mild white cheese dip", "rotisserie chicken", "salsa", "red onion", "avocado", "queso fresco", "fresh cilantro"] },
    { id: 9, name: "Chicken Piccata", ings: ["chicken breasts", "egg", "lemon juice", "flour", "paprika", "garlic powder", "butter", "chicken bouillon cubes", "boiling water"] },
    { id: 10, name: "Chicken Tortilla Soup", ings: ["chicken breasts", "chicken broth", "diced mild tomatoes and green chiles", "frozen Southwest vegetable blend", "enchilada sauce", "garlic", "cumin", "chili powder", "avocado", "shredded Cheddar cheese", "corn tortillas", "olive oil", "salt"] },
    { id: 11, name: "Chicken-Vegetable Rice Noodles", ings: ["rice noodles", "stir fry vegetables", "rotisserie chicken", "teriyaki sauce", "cashews"] },
    { id: 12, name: "Chicken with Honey-Roasted Tomatoes", ings: ["chicken breasts", "salt", "pepper", "olive oil", "grape tomatoes", "honey", "balsamic vinegar", "fresh basil"] },
    { id: 13, name: "Chipotle Chicken and Rice Soup", ings: ["onion", "jalapeno peppers", "chicken breasts", "taco seasoning mix", "ground chipotle chile pepper", "chicken broth", "fire roasted diced tomatoes", "limes", "white rice", "black beans", "fresh cilantro"] },
    { id: 14, name: "Cornish Hen", ings: ["Cornish hen", "flour"] },
    { id: 15, name: "Creamy Lemon Chicken Pasta", ings: ["linguine", "chicken breasts", "butter", "cream cheese", "shredded Parmesan cheese", "lemon"] },
    { id: 16, name: "Crispy Chicken", ings: ["crisp rice cereal", "flour", "salt", "poultry seasoning", "butter", "chicken breasts"] },
    { id: 17, name: "Easy Garlic-Pepper Chicken", ings: ["chicken breasts", "Montreal steak seasoning", "olive oil"] },
    { id: 18, name: "Easy Tex-Mex Chicken", ings: ["white rice", "chicken breasts", "taco seasoning mix", "olive oil", "black beans", "frozen corn kernels", "salsa"] },
    { id: 19, name: "Fajita Chicken", ings: ["chicken thighs", "salt", "pepper", "bell peppers", "onion", "cumin", "chili powder", "garlic powder", "pepper Jack cheese", "fresh cilantro"] },
    { id: 20, name: "Grilled Mojo Chicken Breasts", ings: ["oranges", "garlic", "chipotle peppers in adobo sauce", "fresh thyme", "salt", "chicken breasts"] },
    { id: 21, name: "Italian Chicken Bowls", ings: ["orzo", "olive oil vinaigrette", "chicken thighs", "Italian seasoning", "garlic powder", "salt", "pepper", "grape tomatoes", "olive oil", "red onion", "mozzarella cheese pearls"] },
    { id: 22, name: "Italian Chicken Spaghetti Soup", ings: ["mirepoix", "olive oil", "chicken broth", "Italian seasoning", "kosher salt", "pepper", "rotisserie chicken", "whole grain spaghetti", "sun dried tomatoes", "Parmesan cheese"] },
    { id: 23, name: "Italian Chicken Wings", ings: ["chicken wings", "olive oil", "dried oregano", "garlic salt", "onion powder", "cayenne pepper", "chicken broth"] },
    { id: 24, name: "Montreal Chicken", ings: ["chicken breasts", "Montreal steak seasoning", "olive oil"] },
    { id: 25, name: "Pesto Chicken and Asparagus Pasta", ings: ["rotini pasta", "asparagus", "rotisserie chicken", "pesto", "half and half", "water", "onion powder", "garlic powder", "salt", "pepper"] },
    { id: 26, name: "Roasted Chicken Thighs", ings: ["red grapes", "red onions", "fresh thyme", "olive oil", "chicken thighs", "salt", "pepper"] },
    { id: 27, name: "Rosemary-Garlic Chicken Thighs", ings: ["chicken thighs", "olive oil", "fresh rosemary", "garlic powder", "salt"] },
    { id: 28, name: "Sheet Pan Chicken Fajitas", ings: ["chicken breasts", "bell peppers", "onion", "Roma tomatoes", "olive oil", "Mexican seasoning", "romaine lettuce", "avocados", "limes"] },
    { id: 29, name: "Sheet Pan Sesame Chicken and Broccoli", ings: ["sesame oil", "soy sauce", "gochujang", "chicken thighs", "broccoli florets", "red bell peppers", "honey", "sesame seeds"] },
    { id: 30, name: "Skillet Lemon Chicken", ings: ["chicken breasts", "dried thyme", "salt", "pepper", "butter", "chicken broth", "lemon juice", "honey", "Dijon mustard", "lemon"] },
    { id: 31, name: "Spaghetti in Garlic Gravy with Chicken and Cherry Tomatoes", ings: ["spaghetti pasta", "chicken breast fillets", "fresh thyme", "fresh rosemary", "lemon zest", "lemon juice", "extra virgin olive oil", "coarse salt", "black pepper", "butter", "garlic", "all-purpose flour", "chicken stock", "fresh basil", "parsley", "parmesan cheese", "cherry tomatoes"] },
    { id: 32, name: "Spring Chicken and Vegetables", ings: ["chicken breasts", "salt", "pepper", "olive oil", "fresh parsley", "white wine vinegar", "green onions", "asparagus", "frozen green peas", "goat cheese", "whole grain linguine", "butter", "panko breadcrumbs"] },
    { id: 33, name: "Stovetop Chicken and Potatoes", ings: ["chicken thighs", "salt", "pepper", "olive oil", "red potatoes", "Italian seasoning", "garlic", "heavy cream", "butter", "lemon juice", "frozen green peas"] },
    { id: 34, name: "Teriyaki Chicken and Vegetables", ings: ["chicken breasts", "canola oil", "zucchini", "red bell pepper", "red onion", "mushrooms", "soy sauce", "honey", "sesame oil", "sesame seeds", "cornstarch"] },

    // --- BEEF ---
    { id: 35, name: "All-American Burger Bowls", ings: ["lean ground beef", "chili sauce", "Worcestershire sauce", "yellow mustard", "sharp Cheddar cheese", "romaine lettuce hearts", "tomatoes", "red onion", "Crinkle cut Fries"] },
    { id: 36, name: "Ancho Chile Pot Roast", ings: ["ancho chile peppers", "boiling water", "chuck roast", "avocado oil", "Onion", "Minced garlic", "sweet potatoes", "beef bone broth", "Fresh thyme", "bay eaves", "Arrowroot", "Fresh parsley"] },
    { id: 37, name: "Balsamic-Mustard Flank Steak", ings: ["flank steak", "garlic", "salt", "pepper", "avocado oil", "balsamic vinegar", "Dijon mustard"] },
    { id: 38, name: "Barbecue Flank Steak and Corn Salad", ings: ["flank steak", "barbecue sauce", "corn", "avocados", "Roma tomatoes"] },
    { id: 39, name: "Beef and Broccoli Lo Mein", ings: ["lo mein noodles", "broccoli florets", "flank steak", "olive oil", "shredded carrots", "brown sugar", "soy sauce", "hoisin sauce", "dark sesame oil", "garlic powder", "crushed red pepper"] },
    { id: 40, name: "Beef Roast with Vegetables", ings: ["carrots", "parsnips", "turnips", "celery", "eye of round roast", "avocado oil", "fresh thyme", "garlic", "kosher salt", "pepper", "leeks"] },
    { id: 41, name: "Bistro Flank Steak", ings: ["flank steak", "pepper", "dry mustard", "garlic powder", "dried oregano", "salt"] },
    { id: 42, name: "Chinese Pepper Steak", ings: ["round steak", "oil", "garlic", "green bell peppers", "diced tomatoes", "onion", "sugar", "soy sauce", "cornstarch", "water"] },
    { id: 43, name: "Coffee-braised Beef Brisket", ings: ["ancho chile powder", "unsweetened baking cocoa", "dried oregano", "ground cumin", "salt", "ground chipotle chilepepper", "beef brisket", "red onion", "garlic", "brewed coffee", "balsamic vinegar"] },
    { id: 44, name: "Enchilada Soup", ings: ["ground beef", "pinto beans", "onion", "jalapeño peppers", "garlic", "chicken broth", "petite diced tomatoes", "chili powder", "ground cumin", "tortilla strips"] },
    { id: 45, name: "Garlic Butter Steak and Potatoes", ings: ["red potato wedges and onions", "garlic", "top sirloin steak", "pepper", "salt", "butter", "spring mix", "tomatoes", "cucumber", "mozzarella cheese pearls", "Italian herb croutons", "creamy Italian dressing"] },
    { id: 46, name: "Herb Butter Bistro Steaks", ings: ["New York strip steaks", "salt", "pepper", "olive oil", "shallots", "red wine vinegar", "lemon juice", "butter", "fresh parsley", "fresh thyme leaves"] },
    { id: 47, name: "Italian Beefy Pasta Bake", ings: ["ground beef", "onion", "red bell pepper", "fire roasted diced tomatoes", "chicken broth", "Italian seasoning", "pepper", "salt", "whole wheat penne pasta", "Parmesan cheese"] },
    { id: 48, name: "Kung Pao Beef and Vegetables", ings: ["microwavable long grain white rice", "ground beef", "frozen broccoli stir fry vegetables", "olive oil", "kung pao sauce"] },
    { id: 49, name: "Mario’s Grilled Steak", ings: ["Steak", "Seasoning"] },
    { id: 50, name: "Mississippi Pot Roast", ings: ["sirloin tip roast", "Ranch dressing mix", "Au Jus mix", "butter", "peperoncini peppers"] },
    { id: 51, name: "Oven Roast", ings: ["flour", "top round", "salt", "pepper", "potatoes", "onions", "celery", "carrots", "beef bouillon cube", "boiling water", "tomato soup"] },
    { id: 52, name: "Sheet Pan Herbed Flank Steak", ings: ["flank steak", "olive oil", "fresh rosemary", "fresh thyme", "garlic"] },
    { id: 53, name: "Sheet-Pan Steak with Broccolini", ings: ["balsamic vinegar", "avocado oil", "whole grain Dijon mustard", "garlic", "kosher salt", "pepper", "skirt steak", "Broccolini", "walnuts"] },
    { id: 54, name: "Spaghetti with Ground Beef", ings: ["Pasta", "Ground beef", "Pasta sauce"] },
    { id: 55, name: "Spicy Beef Ramen", ings: ["spicy beef ramen soup", "beef broth", "water", "skirt steak", "olive oil", "garlic", "crushed red pepper", "green onions", "hard cooked eggs"] },
    { id: 56, name: "Spicy Ginger Steak", ings: ["sirloin steaks", "soy sauce", "ginger", "Asian chili garlic paste", "rice vinegar", "honey", "sesame oil", "baby bok choy"] },
    { id: 57, name: "Three Pepper Pot Roast", ings: ["red bell pepper", "green bell pepper", "chuck roast", "au jus gravy mix", "pepperoncini salad peppers", "pepperoncini juice", "butter"] },

    // --- PORK ---
    { id: 58, name: "Brown Sugar Pork Roast", ings: ["brown sugar", "salt", "pepper", "pork shoulder roast", "onion", "garlic", "bay leaf", "chicken broth", "white wine vinegar"] },
    { id: 59, name: "Bruschetta Pork Chops", ings: ["pork chops", "salt", "pepper", "olive oil", "grape tomatoes", "bruschetta topping", "fresh basil", "garlic", "fresh thyme", "balsamic vinegar"] },
    { id: 60, name: "Creole Pork Chops", ings: ["pork chops", "Creole seasoning", "salt", "pepper", "olive oil", "celery", "onion", "green bell pepper", "grape tomatoes", "garlic", "fresh parsley"] },
    { id: 61, name: "Grilled Lemon-Pepper Pork Chops", ings: ["olive oil", "lemon pepper seasoning", "pork loin chops"] },
    { id: 62, name: "Grilled Greek Pork Medallions", ings: ["pine nuts", "garlic", "all purpose flour", "Greek seasoning", "kosher salt", "pepper", "pork tenderloins", "olive oil"] },
    { id: 63, name: "Honey Garlic Pork Tenderloin", ings: ["pork tenderloins", "salt", "pepper", "garlic", "vegetable oil", "honey", "soy sauce", "rice vinegar", "green onions"] },
    { id: 64, name: "Lemon and Herb Pork Tenderloin", ings: ["olive oil", "lemon juice", "fresh thyme", "fresh rosemary", "garlic", "pork tenderloins", "salt", "pepper"] },
    { id: 65, name: "Marinated Pork chops -Dave Hills", ings: ["Marinated pork chops"] },
    { id: 66, name: "Mario’s Grilled Pork Chops", ings: ["Pork Chops", "Seasoning"] },
    { id: 67, name: "One Pot Pork Chops and Rice", ings: ["pork chops", "smoked paprika", "salt", "olive oil", "bell pepper mix", "grape tomatoes", "chicken broth", "fresh thyme", "instant brown rice"] },
    { id: 68, name: "Orange-Balsamic Pork Tenderloin", ings: ["orange", "balsamic vinegar", "olive oil", "pork tenderloins", "garlic", "fresh thyme", "seasoned pepper", "kosher salt"] },
    { id: 69, name: "Pork and Apples", ings: ["boneless pork chops", "apples", "brown sugar", "cinnamon", "butter"] },
    { id: 70, name: "Pork Chops with Balsalmic-Bacon Sauce", ings: ["bacon", "pork chops", "salt", "pepper", "red onion", "garlic", "cornstarch", "chicken broth", "balsamic vinegar", "whole grain mustard"] },
    { id: 71, name: "Pork Tenderloin with Chimichurri", ings: ["pork tenderloins", "salt", "black pepper", "fresh parsley", "olive oil", "red wine vinegar", "fresh oregano", "crushed red pepper", "garlic"] },
    { id: 72, name: "Rosemary-Mustard Pork Chops", ings: ["pork chops", "salt", "pepper", "olive oil", "Dijon mustard", "fresh rosemary", "red wine vinegar", "garlic", "honey"] },
    { id: 73, name: "Skillet Salsa Pork Chops", ings: ["pork chops", "garlic salt", "cumin", "olive oil", "fresh salsa", "lemon juice"] },
    { id: 74, name: "Slow Cooker Pork Ramen", ings: ["pork shoulder", "Kosher salt", "canola oil", "yellow onion", "garlic", "fresh ginger", "chicken broth", "leek", "mushrooms", "soy sauce", "sesame oil", "chile oil", "ramen noodles", "eggs", "green onions"] },
    { id: 75, name: "Smoky Pork Tenderloin, Sweet Potatoes and Broccoli", ings: ["pork tenderloins", "olive oil", "smoked paprika", "salt", "pepper", "sweet potatoes", "garlic powder", "broccoli florets"] },
    { id: 76, name: "Strawberry Pork Chops", ings: ["pork chops", "Frozen strawberries", "Cooking oil"] },
    { id: 77, name: "Tex-Mex Pork Chops", ings: ["pork chops", "olive oil", "taco seasoning mix", "salsa verde"] },
    { id: 78, name: "Tuscan Pork Tenderloin", ings: ["Italian seasoning", "garlic powder", "pork tenderloins", "olive oil"] },

    // --- SEAFOOD & PASTA ---
    { id: 79, name: "Bruschetta Pasta", ings: ["whole grain linguine", "baby spinach", "garlic", "olive oil", "tomatoes", "fresh basil", "balsamic vinegar", "salt", "pepper", "Parmesan cheese"] },
    { id: 80, name: "Creole Shrimp", ings: ["lemons", "shrimp", "Creole seasoning", "olive oil", "light butter with canola oil"] },
    { id: 81, name: "Italian Shrimp and Pasta", ings: ["fettuccine", "butter", "Italian dressing mix", "shrimp", "grape tomatoes"] },
    { id: 82, name: "Lowcountry Sausage and Shrimp Skillet", ings: ["smoked turkey sausage", "onion", "yellow bell pepper", "red bell pepper", "garlic", "olive oil", "zucchini", "fire roasted diced tomatoes", "chicken broth", "shrimp"] },
    { id: 83, name: "Pesto Pasta with Tomatoes & Mozzarella", ings: ["linguine", "pesto", "grape tomatoes", "mozzarella cheese pearls"] },
    { id: 84, name: "Red Beans and Rice", ings: ["smoked sausage link", "dried red beans", "onion", "green bell pepper", "stalks celery", "Cajun seasoning", "chicken broth", "white rice"] },
    { id: 85, name: "Sheet Pan Creole Shrimp and Sausage", ings: ["onion", "red bell pepper", "yellow bell pepper", "kielbasa sausage", "avocado oil", "Cajun Creole seasoning", "salt", "shrimp", "grape tomatoes", "fresh parsley"] },
    { id: 86, name: "Shrimp Caesar Pasta", ings: ["spaghetti", "shrimp", "olive oil", "vinaigrette-style Caesar dressing", "fresh parsley"] },
    { id: 87, name: "Shrimp Scampi", ings: ["whole grain angel hair pasta", "garlic", "olive oil", "shrimp", "white wine", "fresh lemon juice", "butter", "crushed red pepper", "fresh parsley"] },
    { id: 88, name: "Spicy Orange-Glazed Shrimp", ings: ["orange juice", "soy sauce", "crushed red pepper", "shrimp", "salt", "olive oil", "green onions"] },
    { id: 89, name: "Tortellini Florentine Soup", ings: ["plant based sausage links", "garlic", "vegetable juice", "vegetable broth", "cheese tortellini", "frozen chopped spinach"] },
    { id: 90, name: "Tacos de Mario", ings: ["Tortillas", "Marinated meat (El Paraiso)", "Onion", "Cilantro", "tomatoes"] }
];
